<a href="https://colab.research.google.com/github/w25536/kaggle/blob/main/High_Peformance_Rainfall_Predction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
url = 'https://github.com/w25536/kaggle/raw/main/csv/weatherAUS.csv'
data = pd.read_csv(url)

In [6]:
data

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,5/18/2009,Hobart,5.1,14.3,0.0,1.8,8.9,NW,30.0,WSW,...,47.0,1023.1,1022.2,1.0,1.0,9.1,13.3,No,0.0,No
1,7/3/2009,Launceston,1.1,14.5,0.4,NaN,NaN,SSW,50.0,E,...,46.0,1001.5,1002.4,NaN,NaN,1.3,13.7,No,0.0,No
2,2/18/2010,Williamtown,19.7,26.2,0.0,7.2,7.2,SSE,41.0,SSE,...,50.0,1020.9,1021.9,6.0,4.0,22.7,24.4,No,0.2,No
3,3/4/2010,PerthAirport,16.6,28.0,0.0,9.0,11.3,SW,54.0,SSE,...,41.0,1018.3,1014.9,6.0,1.0,20.0,26.1,No,0.0,No
4,9/9/2010,GoldCoast,14.6,25.3,0.0,NaN,NaN,NNW,43.0,WNW,...,67.0,1020.3,1015.0,NaN,NaN,22.2,22.6,No,0.4,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36876,6/14/2011,Perth,10.1,14.2,7.4,3.4,0.0,NNE,46.0,NNE,...,81.0,1016.2,1014.5,7.0,8.0,10.4,13.9,Yes,9.0,Yes
36877,9/24/2010,PerthAirport,6.3,26.0,0.0,5.0,10.6,W,37.0,N,...,45.0,1024.2,1021.5,1.0,1.0,18.4,23.5,No,0.0,No
36878,5/6/2011,Darwin,20.5,31.7,0.0,7.0,11.1,E,37.0,E,...,39.0,1012.6,1009.0,2.0,5.0,25.7,30.5,No,0.0,No
36879,10/12/2010,Perth,6.3,23.3,0.0,5.2,11.6,SSW,39.0,E,...,41.0,1023.9,1019.9,0.0,1.0,16.4,20.9,No,0.0,No
36880,12/22/2010,Nuriootpa,9.4,26.3,0.0,4.8,12.2,SE,35.0,ENE,...,28.0,1017.5,1014.7,4.0,4.0,16.7,25.3,No,0.0,No